# Generated by Django 5.2.4 on 2025-08-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
